### ISSUE TITLE
cl1 and cl2 not read correctly for unstructured model with CLN

### ISSUE THREAD

**Issue by langevin-usgs** [MODFLOW-USGS/mfusg#39]
Bug appears to be in U1DRELNJA.  cl1 and cl2 are filled while scrolling through JA array, which may have CLN node numbers in them.  This model dies in debug mode with an array bounds exceeded in U1DRELNJA.

[model01.broken.cln.zip](https://github.com/OGW-USGS/mfusg/files/2461790/model01.broken.cln.zip)

**Comment by sorab** [comment]
Reading data in symmetric formats has some issues in U1DRELNJA.  Fixed.

**Comment by christianlangevin** [comment]
Turns out this model has a fatal flaw in it.  In the DISU package the user had set IDSYMRD to 1, and provided cl1 and cl2 arrays and also the FAHL array.  But these arrays were not set up for IDSYMRD.  It looks like they came from gridgen, which outputs the full NJA arrays.  So really, CL1 is CL12, and it has a diagonal position.  So in order to the test model here, IDSYMRD should be set to zero, and the CL2 array should be removed from the DISU package.

**Comment by sorab** [comment]
Keep this issue closed, but it did identify a bug with the symmetric read. Symmetric reads have no diagonal term (none of the zeros), so the CL1 and CL2 were modified to remove the diagonal term (both are not identical so it seems that they were distinct and not a copy of an asymmetric CL1CL2). With that change, it did run, and it did converge too. Attached are the CL1 and CL2 files that were for the symmetric read.

Sorab

spanday@gsienv.com<mailto:spanday@gsienv.com>
Phone: 713-522-6300 x 335
Direct: 281-833-9194
Cell: 571-238-6916

**Comment by christianlangevin** [comment]
I see that you modified cl1 and cl2, but what about fahl?  When IDSYMRD is 1, it is also read as symmetric without the diagonal zeros.  So this still isn't quite right, and I still see FAHL values for valid connections (1 to 2, for example) where FAHL is zero.  

Also, how did you modify cl1 and cl2?  Did you just remove the leading zeros?  If so, then I don't think this is quite right either, because you also need to remove the row entries where J < N.

I agree that we should keep this problem in our test suite, so I'm going to add the symmetric read case as a separate test, once we agree on what files we should use for CL1, CL2, and FAHL.

**Comment by sorab** [comment]
I agree. I did not check the problem itself. Just that symmetric read was working. I too was surprised that the problem then ran and converged.
Sorab


spanday@gsienv.com<mailto:spanday@gsienv.com>
Phone: 713-522-6300 x 335
Direct: 281-833-9194
Cell: 571-238-6916
